#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro plugin install <plugin_name> [plugin_version]"
  echo ""
}

check_plugin() {
  local plugin_name=$1
  local plugin_url="${ZMICRO_PLUGIN_REPO_PREFIX}${plugin_name}"
  
  local status_code=$(curl -o /dev/null -s -w "%{http_code}\n" $plugin_url)
  if [ "$status_code" != "200" ]; then
    log_error "plugin $plugin_name not found"
    exit 1
  fi
}

core() {
  if [[ $# -eq 0 ]]; then
    help
    exit 0
  fi

  local plugin_name=$1
  local plugin_version=$2
  local plugin_url="${ZMICRO_PLUGIN_REPO_PREFIX}${plugin_name}"

  check_plugin $plugin_name $plugin_version

  zmicro plugin add $plugin_name $plugin_url $plugin_version
}

run() {
  core $@
}

run $@
