#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro plugin update <plugin_name>"
  echo ""
  echo "Options"
  echo "  -f, --force   Force update"
}

core() {
  while [[ $# -gt 0 ]]; do
    local key=$1
    local value=$2
    case $key in
    -h | --help)
      help
      shift # past key
      exit 0
      ;;
    *)
      # echo "ERROR: unknown parameter \"$key\""
      # help
      # exit 1
      break
      ;;
    esac
  done

  plugin::update $@
}

run() {
  core $@
}

run $@
