#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro plugin update <plugin_name>"
  echo ""
}

core() {
  if [[ $# -eq 0 ]]; then
    help
    exit 0
  fi

  while [[ $# -gt 0 ]]; do
    local key=$1
    local value=$2
    case $key in
    -h | --help)
      help
      shift # past key
      exit 0
      ;;
    *)
      # echo "ERROR: unknown parameter \"$key\""
      # help
      # exit 1
      break
      ;;
    esac
  done

  local plugin_name=$1
  
  local plugin_path=$ZMICRO_PLUGIN_PATH/$plugin_name
  if [ ! -d $plugin_path ]; then
    log "[$(timestamps)][plugin] not found"
    exit 0
  fi

  log_debug "[$(timestamps)][plugin] update $plugin_name"

  # Update @TODO
  cd $plugin_path
  git pull origin master >> $ZMICRO_LOG_COMMON_PATH 2>&1
  if [ "$?" != "0" ]; then
    log_error "[$(timestamps)][plugin] update error $plugin_name ..."
    exit 1
  fi
  cd - >> /dev/null 2>&1

  # register
  plugin_register $plugin_name

  log_success "[$(timestamps)][plugin] update success $plugin_name"
}

run() {
  core $@
}

run $@
