#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro plugin version <plugin_name>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    log::error "plugin name is required"
    exit 1
  fi

  # plugin::get_version $name
  plugin::version_echo $name
}

run() {
  core $@
}

run $@
