#!/bin/bash
export ZMICRO_HOME=$HOME/.zmicro

if [ ! -d "$ZMICRO_HOME" ]; then
  git clone https://github.com/zcorky/zmicro.git $ZMICRO_HOME
fi

. $ZMICRO_HOME/config/config
$ZMICRO_HOME/bin/zmicro init

echo ""
echo "First install, you should source profile:"
echo "  bash: source \$HOME/.bashrc"
echo "  zsh: source \$HOME/.zshrc"
echo "Then run update:"
echo "  zmicro update"
echo ""
