#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro machine frp server <args...>"
  echo ""
}

dependencies_check() {
  which frps >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    return
  fi

  zmicro package install frp
}

core() {
  dependencies_check

  frps $@
}

run() {
  core $@
}

run $@
