#!/bin/bash
PYTHON_VERSION=3.9

which python3 >>/dev/null 2>&1
if [ "$?" != "0" ]; then
  # Ubuntu Python 3.9
  #   https://www.liquidweb.com/kb/how-to-install-and-update-python-to-3-9-in-ubuntu/
  #   sudo add-apt-repository ppa:deadsnakes/ppa
  #   sudo apt update
  #
  pm install -yqq python3
fi

_pip() {
  local command=$1
  # local args=${@:2}
  local args=$2

  python3 -m pip -h >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -yqq python3-pip
  fi

  case $command in
  install)
    python3 -m pip install -i https://pypi.douban.com/simple/ $args
    ;;
  *)
    python3 -m pip $command $args
    ;;
  esac
}

_pip install --upgrade pip
_pip install ipython
_pip install virtualenv
_pip install virtualenvwrapper

# Env
[[ -f "$HOME/.zshrc" ]] &&
  XSHRC="$HOME/.zshrc" ||
  XSHRC="$HOME/.bashrc"

cat $XSHRC | grep VIRTUALENVWRAPPER >>/dev/null 2>&1
if [ "$?" != "0" ]; then
  cat <<EOF >>$XSHRC

# VIRTUALENVWRAPPER
export VIRTUALENVWRAPPER_PYTHON=\$(which python3)
# Ubuntu 20
# source $HOME/.local/bin/virtualenvwrapper.sh
# Other
# source $(which virtualenvwrapper.sh)
alias workon="source \$(which virtualenvwrapper.sh) && workon"
EOF
fi
