#!/bin/bash

echo "Install Tmux ..."
pm install -yqq tmux

# echo "Config Tmux ..."
# wget -O - https://raw.githubusercontent.com/whatwewant/config-tmux-for-mac/master/install | bash

PROGRAM_NAME=tmux
TMUX_HOME=~/.tmux
DESTINATION=$TMUX_HOME/plugins/tpm
TMUX_CONF=~/.tmux.conf
TMUX_PLUGIN_MANAGE_URL="https://github.com/tmux-plugins/tpm.git"

which tmux >> /dev/null
if [ "$?" != "0" ]; then
  echo "Install tmux package ..."
  pm install -yqq tmux
fi

which wget >> /dev/null
if [ "$?" != "0" ]; then
  echo "Install wget ..."
  pm install -yqq wget
fi

# Backup
[[ ! -d ~/.backup ]] && mkdir ~/.backup
if [ -f $TMUX_CONF ]; then
    echo "Backup Tmux Configure to $HOME/.backup ..."
    [[ ! -d $TMUX_HOME ]] && mkdir $TMUX_HOME
    mv $TMUX_CONF $TMUX_HOME

    tar -zcvf ~/.backup/tmux-$(date +%Y-%m-%d-at-%H-%M).tgz  $TMUX_HOME >> /dev/null 2>&1
fi

rm -rf $TMUX_HOME* >> /dev/null 2>&1

# DESTINATION
echo "Install tmux plugin manager - tpm ..."
git clone $TMUX_PLUGIN_MANAGE_URL $DESTINATION >> /dev/null 2>&1

# Config file .tmux.conf
echo "Config tmux config ..."
wget https://whatwewant.github.io/confs/tmux.conf -O $TMUX_CONF >> /dev/null 2>&1

# Reload TMUX environment so TPM is sourced:
echo "Reload TMUX environment ..."
# tmux source-file $TMUX_CONF
#
# Fix: https://stackoverflow.com/questions/41326985/tmux-no-server-running-on-private-tmp-tmux-502-default
tmux start-server \; source-file $TMUX_CONF

# Manual to click prefix + I to download tmux plugins
echo "Now You need munual to click prefix + I to download tmux plugins"