#!/bin/bash
# Version NodeJS LTS: v14

install() {
  pm install -yy ${@}
}

update() {
  pm update -y
}

which vim >> /dev/null 2>&1
if [ "$?" != "0" ]; then
  install vim
fi

# Dev Mode
if [ "$MODE" == "development" ]; then
  exit 0
fi

echo "Install Vim ..."
if [ -f ~/.vimrc ]; then
  echo "Vim already installed."
  exit 0  
fi

[[ -d ~/.vim ]] || mkdir ~/.vim

# tmp dir
[[ -d /tmp/v-tmp ]] || mkdir /tmp/v-tmp

# .vimrc
cd /tmp/v-tmp
[[ -d /tmp/v-tmp/rc ]] || git clone https://github.com/whatwewant/config-vim-for-mac.git
cd -

# backup origin vimrc file
[[ -f ~/.vimrc-bak ]] || ([[ -f ~/.vimrc ]] && cp ~/.vimrc ~/.vimrc-bak)
mv /tmp/v-tmp/config-vim-for-mac/.vimrc ~/.vimrc

# vim pulgin controller - vundle
[[ -d ~/.vim/bundle/Vundle.vim ]] || git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# colors schemes
cd /tmp/v-tmp
[[ -d /tmp/v-tmp/vim-colorschemes ]] || git clone https://github.com/flazz/vim-colorschemes.git
[[ -d ~/.vim/colors ]] || mv /tmp/v-tmp/vim-colorschemes/colors ~/.vim/
cd -

# fonts for airline
cd  /tmp/v-tmp
[[ -d /tmp/v-tmp/fonts ]] || git clone https://github.com/powerline/fonts.git
cd fonts
sh ./install.sh
cd -

# install vim plugins
vim +PluginInstall! +qall

# rm tmp dir
rm -rf /tmp/v-tmp
