#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro login docker <registry> <username> <password>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  login::docker $@
}

run() {
  core $@
}

run $@
