#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro login docker <username> <password> <registry>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  login::docker $@
  if [ "$?" != "0" ]; then
    log:error "failed to login docker"
  else
    log::success "success to login docker"
  fi
}

run() {
  core $@
}

run $@
