#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro login git <registry> <username> <password>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local registry=$1
  local username=$2
  local password=$3

  if [ -z "$registry" ]; then
    log::error "[$(timestamp)] registry is required"
    return 1
  fi

  if [ -z "$username" ]; then
    os::inquirer username "text" "git username"
  fi

  if [ -z "$password" ]; then
    os::inquirer password "text" "git password"
  fi

  login::git $registry $username $password
  if [ "$?" != "0" ]; then
    log::error "failed to login git"
  else
    log::success "success to login git"
  fi
}

run() {
  core $@
}

run $@
