#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro login git <registry> <username> <password>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  login::git $@
  if [ "$?" != "0" ]; then
    log:error "failed to login git"
  else
    log::success "success to login git"
  fi
}

run() {
  core $@
}

run $@
