#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro login npm <registry> <username> <password> <email>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  login::npm $@
  if [ "$?" != "0" ]; then
    log::error "failed to login npm"
  else
    log::success "success to login npm"
  fi
}

run() {
  core $@
}

run $@
