#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro fix permissions"
}

core() {
  # log: fix all user
  log::fix_permissions

  # zmicro fix current user
  sudo chown -R $USER $ZMICRO_HOME
  log::success "[$(timestamp)] Permission fixed."
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core $@
}

run $@
