#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro fix permissions"
}

core() {
  os::fix_permissions
  log::success "[$(timestamp)] Permission fixed."
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core $@
}

run $@
