#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro machine id"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  os_machine_id
}

run() {
  core $@
}

run $@
