#!/bin/bash

DEFAULT_THRESHOLD_PERCENT=90

help() {
  echo "Usage:"
  echo "  zmicro machine mem monitor"
  echo ""
  echo "Options:"
  echo "  -e, --exec <COMMAND>  Run command in threshold percent"
  echo "  -t, --threshold       Threshold, unit: percent (0 - 100), default: 90"
}

core() {
  local command=""
  local threshold_percent=$DEFAULT_THRESHOLD_PERCENT

  while [[ $# -gt 0 ]]; do
    local key=$1
    local value=$2

    # echo "key: $key, value: $value"
    case $key in
      -h | --help)
        help
        exit 0
        ;;
      -e | --exec)
        command=$value
        shift # past key
        shift # past value

        # @TODO zmicro machine mem monitor --exec "zmicro machine ip" -t 90
        local maybe_part_of_command=$1
        while true; do
          # if not start with -, it is a part of command
          echo $maybe_part_of_command | grep "^-" >> /dev/null 2>&1
          if [ "$?" = "0" ]; then
            break
          fi

          # echo "$maybe_part_of_command ..."
          shift
          command="${command} ${maybe_part_of_command}"
          maybe_part_of_command=$1
        done
        ;;
      -t | --threshold)
        threshold_percent=$value
        shift # past key
        shift # past value
        ;;
      *)
        echo "ERROR: unknown parameter \"$key\""
        help
        exit 1
        ;;
    esac
  done

  while true; do
    local usage=$(zmicro machine mem usage)
    if [ $usage -gt $threshold_percent ]; then
      log_info "[$(timestamp)] memory usage(${usage}%) reached threshold percent($kill_percent%), run: ${command}"
      eval $command
    else
      echo "[$(timestamp)] memory usage: $usage%"
    fi

    sleep 1
  done
}

run() {
  core $@
}

run $@
