#!/bin/bash

DEFAULT_THRESHOLD_PERCENT=90

help() {
  echo "Usage:"
  echo "  zmicro machine mem monitor"
  echo ""
  echo "Options:"
  echo "  -e, --exec <COMMAND>  Run command in threshold percent"
  echo "  -t, --threshold       Threshold, unit: percent (0 - 100), default: 90"
}

core() {
  local command=""
  local threshold_percent=$DEFAULT_THRESHOLD_PERCENT

  while [[ $# -gt 0 ]]; do
    local key=$1
    local value=$2
    case $key in
      -h | --help)
        help
        exit 0
        ;;
      -e | --exec)
        command=$value
        shift # past key
        shift # past value
        ;;
      -t | --threshold)
        threshold_percent=$value
        shift # past key
        shift # past value
        ;;
      *)
        echo "ERROR: unknown parameter \"$key\""
        help
        exit 1
        ;;
    esac
  done

  while true; do
    local usage=$(zmicro machine mem usage)
    if [ $usage -gt $threshold_percent ]; then
      log_info "memory usage(${usage}%) reached threshold percent($kill_percent%), run: ${command}"
      eval $command
    else
      echo "memory usage: $usage%"
    fi

    sleep 1
  done
}

run() {
  core $@
}

run $@
