#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro clean docker"
}

core() {
  while [ "$1" != "" ]; do
    case $1 in
    -h | --help)
      help
      exit
      ;;
    -d | --deep)
      export CLEAN_DOCKER_DEEP=true
      shift
      ;;
    *)
      help
      exit 1
      ;;
    esac
    shift
  done

  clean::docker
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core $@
}

run $@
