#!/bin/bash

config_data_dir() {
  if [ ! -d $ZMICRO_APP_DATA_PATH ]; then
    sudo mkdir -p $ZMICRO_APP_DATA_PATH
  fi

  if [ ! -r $ZMICRO_APP_DATA_PATH ] || [ ! -w $ZMICRO_APP_DATA_PATH ]; then
    sudo chown -R $USER $ZMICRO_APP_DATA_PATH
  fi
}

config_data() {
  config_data_dir
}

config_data
