#!/bin/bash

config_data_dir() {
  if [ ! -d $ZMICRO_APP_DATA_PATH ]; then
    sudo mkdir -p $ZMICRO_APP_DATA_PATH
    sudo chown -R $(os_username) $ZMICRO_APP_DATA_PATH
  fi
}

config_data() {
  config_data_dir
}

config_data