#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro config docker"
}

core() {
  config::docker
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core $@
}

run $@
