#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro config git [git_user] [git_email]"
}

core() {
  git::global_setup "$@"
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core "$@"
}

run "$@"
