#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro config list"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  if [ ! -f "$ZMICRO_RC" ]; then
    echo "No config file ($ZMICRO_RC) found"
    exit 0
  fi

  cat $ZMICRO_RC
}

run() {
  core $@
}

run $@
