#!/bin/bash

# config_rc() {
#   # ZMICRO_BIN_PATH: ${ZMICRO_BIN_PATH}
#   export PATH=$ZMICRO_BIN_PATH:$PATH

#   # .bashrc
#   if [ ! -f $HOME/.bashrc ]; then
#     touch $HOME/.bashrc
#   fi
#   cat $HOME/.bashrc | grep ZMICRO_BIN_PATH >>/dev/null 2>&1
#   if [ "$?" != "0" ]; then
#     cat <<EOF >>$HOME/.bashrc

# # ZMICRO
# export ZMICRO_HOME=${ZMICRO_HOME}
# export ZMICRO_BIN_PATH=${ZMICRO_BIN_PATH}
# export PATH=\$ZMICRO_BIN_PATH:\$PATH
# EOF
#   fi

#   if [ ! -f $HOME/.zshrc ]; then
#     touch $HOME/.zshrc
#   fi

#   cat $HOME/.zshrc | grep ZMICRO_BIN_PATH >>/dev/null 2>&1
#   if [ "$?" != "0" ]; then
#     cat <<EOF >>$HOME/.zshrc
    
# # ZMICRO
# export ZMICRO_HOME=${ZMICRO_HOME}
# export ZMICRO_BIN_PATH=${ZMICRO_BIN_PATH}
# export PATH=\$ZMICRO_BIN_PATH:\$PATH
# EOF
#   fi
# }

config_clear() {
  local profile=$1

  if [ -z "$(os_username)" ]; then
    log_error "cannot get username"
    exit 1
  fi

  # # ZMICRO_BIN_PATH: /home/$(os_username)/.zmicro/bin
  # export ZMICRO_HOME=/home/$(os_username)/.zmicro
  # export ZMICRO_BIN_PATH=/home/$(os_username)/.zmicro/bin
  # export PATH=$ZMICRO_BIN_PATH:$PATH

  cat $profile | grep ZMICRO_BIN_PATH >> /dev/null 2>&1
  if [ "$?" = "0" ]; then
    sed -i "/^# ZMICRO_BIN_PATH: \/home\/$(os_username)\/.zmicro\/bin$/d" $profile
    sed -i "/^export ZMICRO_HOME=\/home\/$(os_username)\/.zmicro$/d" $profile
    sed -i "/^export ZMICRO_BIN_PATH=\/home\/$(os_username)\/.zmicro\/bin$/d" $profile
    sed -i "/^export PATH=\$ZMICRO_BIN_PATH:\$PATH$/d" $profile
  fi
}

config_rc() {
  local profile=$1
  if [ ! -f $profile ]; then
    touch $profile
  fi

  cat $profile | grep "export ZMICRO_HOME=${ZMICRO_HOME}" >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    local origin_code=$(cat $profile)
    tee $profile >> /dev/null <<EOF
${origin_code}

# ZMICRO
export ZMICRO_HOME=${ZMICRO_HOME}
export PATH=\$ZMICRO_HOME/bin:\$PATH
EOF
  fi
}

# Global, need root
config_global_rc() {
  local profile=$1

  # if not found, ignore
  if [ ! -f $profile ]; then
    log_error "[$(timestamp)][config_global_rc] profile $profile not found"
    exit 1
  fi

  cat $profile | grep "export ZMICRO_HOME=${ZMICRO_HOME}" >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
#     sudo tee -a $profile >> /dev/null <<EOF
# # ZMICRO
# export ZMICRO_HOME=${ZMICRO_HOME}
# export PATH=\$ZMICRO_HOME/bin:\$PATH
# EOF
    local text=$(cat <<-END
# ZMICRO
export ZMICRO_HOME=${ZMICRO_HOME}
export PATH=\$ZMICRO_HOME/bin:\$PATH 
END
)
    sudo tee -a $profile >> /dev/null <<EOF
${text}
EOF
  fi
}

config_global_rc_ignore_if_not_found() {
  local profile=$1
  if [ ! -f $profile ]; then
    return
  fi

  config_global_rc $profile
}

config_global_rc_force_create_if_not_found() {
  local profile=$1
  if [ ! -f $profile ]; then
    sudo touch $profile
  fi

  config_global_rc $profile
}

# common
config_profile() {
  config_global_rc_force_create_if_not_found /etc/profile.d/zmicro2.sh
}

config_bashrc() {
  # OLD
  config_clear $HOME/.bashrc

  # HOME
  config_rc $HOME/.bashrc

  # # GLOBAL
  # #   ubuntu  20
  # config_global_rc_ignore_if_not_found /etc/bashrc 
  # #   centos  8
  # config_global_rc_ignore_if_not_found /etc/bash.bashrc 
}

config_zshrc() {
  # OLD
  config_clear $HOME/.zshrc

  # HOME
  config_rc $HOME/.zshrc

  # # GLOBAL
  # #   ubuntu 20
  # config_global_rc_ignore_if_not_found /etc/zsh/zprofile 
  # #   centos 8
  # config_global_rc_ignore_if_not_found /etc/zshrc 
}

# https://unix.stackexchange.com/questions/104727/add-a-path-in-path-globally-for-every-user
# if [ -f "/etc/environment" ]; then
#   config_rc /etc/environment
# else
#   config_rc /etc/profile
# fi

config_profile
config_bashrc
config_zshrc