#!/bin/bash

config_rc() {
  # ZMICRO_BIN_PATH: ${ZMICRO_BIN_PATH}
  export PATH=$ZMICRO_BIN_PATH:$PATH

  # .bashrc
  if [ ! -f $HOME/.bashrc ]; then
    touch $HOME/.bashrc
  fi
  cat $HOME/.bashrc | grep ZMICRO_BIN_PATH >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    cat <<EOF >>$HOME/.bashrc

# ZMICRO
export ZMICRO_HOME=${ZMICRO_HOME}
export ZMICRO_BIN_PATH=${ZMICRO_BIN_PATH}
export PATH=\$ZMICRO_BIN_PATH:\$PATH
EOF
  fi

  if [ ! -f $HOME/.zshrc ]; then
    touch $HOME/.zshrc
  fi

  cat $HOME/.zshrc | grep ZMICRO_BIN_PATH >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    cat <<EOF >>$HOME/.zshrc
    
# ZMICRO
export ZMICRO_HOME=${ZMICRO_HOME}
export ZMICRO_BIN_PATH=${ZMICRO_BIN_PATH}
export PATH=\$ZMICRO_BIN_PATH:\$PATH
EOF
  fi
}

config_rc
