#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro config delete <key>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local key=$1
  if [ "$key" = "" ]; then
    log_error "key is required"
    log_error ""
    
    help
    exit 1
  fi

  zmicro_config_remove $key
}

run() {
  core $@
}

run $@
