#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro config timezone [TIMEZONE]"
  echo ""
  echo "    Default timezone: ${TZ}"
}

is_timezone_seted() {
  local tz=$1
  if [ -z $tz ]; then
    log::error "[is_timezone_seted] timezone is required"
    exit 1
  fi

  # @1 TZ env
  if [ -n "$TZ" ]; then
    echo "true"
    return
  fi

  # @2 /etc/timezone
  if [ -f "/etc/timezone" ]; then
    cat /etc/timezone | grep $tz >>/dev/null 2>&1
    if [ "$?" = "0" ]; then
      echo "true"
      return
    fi
  fi

  # @3 timedatectl
  which timedatectl >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo timedatectl show | grep $tz >>/dev/null 2>&1
    if [ "$?" = "0" ]; then
      echo "true"
      return
    fi
  fi

  echo "false"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local _timezone=$1
  local timezone=${_timezone:-$TZ}
  log::debug "timezone: $timezone"

  # Show current timezone
  # timedatectl status

  # List all available timezones
  # timedatectl list-timezones

  # Set timezone
  if [ "$(os::is_docker)" = "true" ]; then
    # @TODO 兼容性不好，目前优先支持 alpine/ubuntu

    # @FIX TimeZone in Docker (alpine)
    #  https://www.cnblogs.com/flipped/p/15808681.html
    if [ ! -f "/usr/share/zoneinfo/${TZ}" ]; then
      # alpine
      which apk >>/dev/null 2>&1
      if [ "$?" = "0" ]; then
        sudo apk add tzdata
      fi

      # ubuntu
      which apt >>/dev/null 2>&1
      if [ "$?" = "0" ]; then
        sudo apk install -y tzdata
      fi

      # centos
      which apt >>/dev/null 2>&1
      if [ "$?" = "0" ]; then
        sudo yum install -y tzdata
      fi

      # @TODO support more
    fi

    if [ -f "/usr/share/zoneinfo/${TZ}" ]; then
      sudo cp /usr/share/zoneinfo/${TZ} /etc/localtime >>/dev/null # 2>&1
    fi

    echo ${TZ} | sudo tee /etc/timezone >>/dev/null 2>&1

    # which apk >>/dev/null 2>&1
    # if [ "$?" = "0" ]; then
    #   sudo apk del tzdata
    # fi

    local BASHRC_PATH=$HOME/.bashrc
    if [ -f $BASHRC_PATH ]; then
      cat $BASHRC_PATH | grep "ZMICRO TIMEZONE" >>/dev/null 2>&1
      if [ "$?" != "0" ]; then
        echo "# ZMICRO TIMEZONE" | sudo tee -a $BASHRC_PATH >>/dev/null 2>&1
        echo "TZ=\"${TZ}\"" | sudo tee -a $BASHRC_PATH >>/dev/null 2>&1
        echo "" | sudo tee -a $BASHRC_PATH >>/dev/null 2>&1
      fi
    fi

    local ZSHRC_PATH=$HOME/.zshrc
    if [ -f $ZSHRC_PATH ]; then
      cat $ZSHRC_PATH | grep "ZMICRO TIMEZONE" >>/dev/null 2>&1
      if [ "$?" != "0" ]; then
        echo "# ZMICRO TIMEZONE" | sudo tee -a $ZSHRC_PATH >>/dev/null 2>&1
        echo "TZ=\"${TZ}\"" | sudo tee -a $ZSHRC_PATH >>/dev/null 2>&1
        echo "" | sudo tee -a $ZSHRC_PATH >>/dev/null 2>&1
      fi
    fi
    return
  fi

  if [ "$(is_timezone_seted $timezone)" = "true" ]; then
    return
  fi

  sudo timedatectl set-timezone $timezone
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)][config] Failed to set timezone: $timezone"
  else
    log::success "[$(timestamp)][config] Current timezone: $timezone"
  fi
}

run() {
  core $@
}

run $@
