FROM archlinux:latest

RUN pacman -Sy && pacman -Syu --noconfirm curl cron

ENV CI=true

RUN curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | bash

RUN zmicro -v

RUN zmicro update -f

RUN zmicro info
