FROM debian:10.0

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y curl

RUN curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | bash

RUN zmicro update -f

RUN zmicro info
