#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro auto update"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # @TODO make sure update
  # zmicro update -a >> /dev/null 2>&1

  zmicro cron create zmicro_auto_update 0 10 _/1 _ _ zmicro update -a >> /dev/null
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] zmicro create auto update error"
    exit 1
  else
    log::success "zmicro will auto update ok at 10:00 AM every day"
  fi
}

run() {
  core $@
}

run $@
