#!/bin/bash

export RED="\e[31m"
export GREEN="\e[32m"
export YELLOW="\e[33m"
export GRAY="\e[37m"
export ENDCOLOR="\e[0m"

if [ "$(os_is_macos)" = "true" ]; then
  RED="\033[31m"
  GREEN="\033[32m"
  YELLOW="\033[33m"
  GRAY="\033[37m"
  ENDCOLOR="\033[0m"
fi

color_success() {
  if [ "$(os_is_support_color)" = "false" ]; then
    echo $@
    return
  fi

  echo -e "${GREEN}${@}${ENDCOLOR}"
}

color_error() {
  if [ "$(os_is_support_color)" = "false" ]; then
    echo $@
    return
  fi

  echo -e "${RED}${@}${ENDCOLOR}"
}

color_warn() {
  if [ "$(os_is_support_color)" = "false" ]; then
    echo $@
    return
  fi

  echo -e "${YELLOW}${@}${ENDCOLOR}"
}

color_disable() {
  if [ "$(os_is_support_color)" = "false" ]; then
    echo $@
    return
  fi

  echo -e "${GRAY}${@}${ENDCOLOR}"
}

color_green() {
  if [ "$(os_is_support_color)" = "false" ]; then
    echo $@
    return
  fi

  echo -e "${GREEN}${@}${ENDCOLOR}"
}

color_red() {
  if [ "$(os_is_support_color)" = "false" ]; then
    echo $@
    return
  fi

  echo -e "${RED}${@}${ENDCOLOR}"
}

color_yellow() {
  if [ "$(os_is_support_color)" = "false" ]; then
    echo $@
    return
  fi

  echo -e "${YELLOW}${@}${ENDCOLOR}"
}

export -f color_success
export -f color_error
export -f color_warn
export -f color_disable

export -f color_green
export -f color_red
export -f color_yellow
