#!/bin/bash

# Has End

commander::get_command_path_internal() {
  local base_command_path=$1
  local pos=2
  local commands=${@:$pos}

  local command_dir="$base_command_path"
  for command in $commands; do
    local command_path=$command_dir/$command
    # log::debug "[$(timestamp)][command] try path: $command_path" >>/dev/null 2>&1
    # command file
    if [ -f "$command_path" ]; then
      # log::debug "[$(timestamp)]$(color::success \"[command] find path: ${command_path}\")"
      pos=$((pos + 1))
      echo "$command_dir:$command:$pos"
      return
    fi

    # command dir
    if [ -d "$command_path" ]; then
      pos=$((pos + 1))
      command_dir=$command_path
      continue
    fi

    #
    break
  done

  # dir
  if [ "$command_dir" != "$base_command_path" ] && [ -d "$command_dir" ]; then
    echo "$command_dir::$pos"
    return 0
  fi

  return 1
}

# command_dir:command_name:pos
commander::get_command_path() {
  local base_command_path=$1
  local command=${@:2}

  local cmd_path=""

  # 1. alias => /_alias
  if [ -f "$base_command_path/_alias/$2" ]; then
    local real_cmd=$(cat $base_command_path/_alias/$2)
    command="$real_cmd ${@:3}"
  fi

  # 1. internal => /_internal
  cmd_path=$(commander::get_command_path_internal $base_command_path/_internal "$command")
  if [ -n "$cmd_path" ]; then
    echo "$cmd_path"
    return
  fi

  # 1.1 internal sub
  #   only for zmicro core, not plugin
  if [ "$base_command_path" = "$ZMICRO_COMMANDS_PATH" ]; then
    cmd_path=$(commander::get_command_path_internal $ZMICRO_SUB_BIN_PATH "$command")
    if [ -n "$cmd_path" ]; then
      echo "$cmd_path"
      return
    fi
  fi

  # 1.2 internal user
  #   only for user custom bins
  if [ "$base_command_path" = "$ZMICRO_COMMANDS_PATH" ]; then
    cmd_path=$(commander::get_command_path_internal $ZMICRO_USER_BIN_PATH "$command")
    if [ -n "$cmd_path" ]; then
      echo "$cmd_path"
      return
    fi
  fi

  # 2. normal
  #   2.1 _run: take over run when _run exist
  #   2.2 normal
  cmd_path=$(commander::get_command_path_internal $base_command_path "$command")
  if [ -n "$cmd_path" ]; then
    echo "$cmd_path"
    return
  fi

  # 3. local
  #  such:
  #   1. zmicro ./xxx.sh
  #   2. env zmicro
  local local_command_path=$command
  if [ -f "$local_command_path" ]; then
    echo "$local_command_path#2"
    return
  fi

  return 1
}

# Get
export -f commander::get_command_path_internal
export -f commander::get_command_path
