#!/bin/bash

os::delay() {
  local fn=$@
  if [ "$fn" = "" ]; then
    log::error "[core][os::delay] fn is required"
    exit 1
  fi

  sleep 1
  eval $fn
}

os::wait() {
  local t=$1
  if [ "$t" = "" ]; then
    t=1
  fi

  sleep $t
}

export -f os::delay
export -f os::wait
