#!/bin/bash

dotenv::load() {
  local filepath=$1
  if [ -z "$filepath" ]; then
    log::error "[dotenv::load] dotenv file is required"
    exit 1
  fi

  if [ ! -f "$filepath" ]; then
    log::error "[dotenv::load] dotenv file ($filepath) not found"
    exit 1
  fi

  config::export "$filepath"
}

dotenv::try_load() {
  local current=$PWD/.env
  if [ -f "$current" ]; then
    # log::info "[dotenv::try_load] found .env($current) ..."

    dotenv::load $current
  fi
}

export -f dotenv::load
export -f dotenv::try_load