#!/bin/bash

function test_git::commit_message() {
  local expected=$(git log -1 --pretty=%B)
  local received=$(git::commit_message)
  
  # testing::expect \
  #   "${FUNCNAME[0]}" \
  #   "to_equal" \
  #   "$expected" \
  #   "$received" 

  # echo "testing::expect \"${FUNCNAME[0]}\" \"to_equal\" \"${expected}\" \"${received}\""

  echo "message: ${expected}"
}

function test_git::commit_hash() {
  local expected=$(git rev-parse --short=9 HEAD)
  local received=$(git::commit_hash)
  
  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received" 
}

function test_git::commit_timestamp() {
  local expected=$(git show -s --format=%cd --date="format:%Y-%m-%d")
  local received=$(git::commit_timestamp)
  
  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received" 
}
