#!/bin/bash

net::is_github_visitable() {
  curl -I https://github.com --connect-timeout 3 >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    echo "false"
  else
    echo "true"
  fi
}

net::is_google_visitable() {
  curl -I https://google.com --connect-timeout 3 >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    echo "false"
  else
    echo "true"
  fi
}

net::is_in_china() {
  if [ "$(net::is_google_visitable)" = "false"]; then
    echo "true"
  else
    echo "false"
  fi
}

net::is_ip() {
  os::is_ip $1
}

net::get_domain_ip() {
  local domain=$1
  if [ -z "$domain" ]; then
    log::error "domain is required"
    exit 1
  fi

  # dig install in ubuntu/centos https://cloud.tencent.com/developer/article/1618605
  if [ "$(os::has_command dig)" = "false" ]; then
    # ubuntu
    if [ "$(os::has_command apt)" = "true" ]; then
      sudo apt install -y dnsutils
    # centos
    elif [ "$(os::has_command yum)" = "true" ]; then
      sudo yum install -y bind-utils
    # alpine
    elif [ "$(os::has_command apk)" = "true" ]; then
      sudo apk add -U bind-tools
    # macos
    elif [ "$(os::has_command brew)" = "true" ]; then
      brew install dnsutils
    # unknown
    else
      log::error "unknown os to install dig"
      exit 1
    fi
  fi

  dig +short $domain @114.114.114.114
}

net::is_url_visitable() {
  local url=$1
  if [ -z "$url" ]; then
    log::error "[net::is_url_visitable] url is required"
    return
  fi

  curl -I $1 --connect-timeout 3 >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    echo "false"
  else
    echo "true"
  fi
}

net::is_port_visitable() {
  local ip=$1
  local port=$2

  if [ -z "$ip" ]; then
    log::error "ip is required"
    exit 1
  fi

  if [ -z "$port" ]; then
    log::error "port is required"
    exit 1
  fi

  # no a valid ip, search dns
  if [ "$(net::is_ip $ip)" = "false" ]; then
    ip=$(net::get_domain_ip $ip)
  fi

  if [ "$(os::has_command nc)" = "true" ]; then
    nc -z -v -n -w 1 $ip $port >>/dev/null 2>&1
    if [ "$?" != "0" ]; then
      echo "false"
    else
      echo "true"
    fi
  else
    # @TODO
    echo "true"
  fi
}

export -f net::is_in_china
export -f net::is_github_visitable
export -f net::is_google_visitable

export -f net::is_ip
export -f net::get_domain_ip

export -f net::is_url_visitable
export -f net::is_port_visitable
