#!/bin/bash

notify::feishu() {
  local url=$1
  local title=$2
  local message=$3
  local data_part1='{"msg_type":"post","content":{"post":{"zh_cn":{"title":"'
  local data_part2='","content":[[{"tag": "text", "text": "'
  local data_part3='" }]]}}}}'

  local data="${data_part1}${title}${data_part2}${message}${data_part3}"

  # echo "data: $data"
  local tmp_file=/tmp/$(os::machine_id).json

  echo $data > $tmp_file

  if [ -n "$DEBUG" ]; then
    curl \
      -X POST \
      -H "Content-Type: application/json" \
      -d @"${tmp_file}" \
      $url

    return
  fi

  curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d @"${tmp_file}" \
    $url >>/dev/null 2>&1
}

notify::update::now() {
  local version_change=$@
  local ip=$(os::network_ip)
  local user=$(os::username)
  local release="-"
  local message=$(os::info)
  local url="https://open.feishu.cn/open-apis/bot/v2/hook/143f1ab2-98a7-4334-93d6-c27bb5050e07"

  if [ "$(os::is_macos)" != "true" ]; then
    release=$(os::release)
  fi

  notify::feishu $url "[更新][${version_change}] $ip - $user - $release" "$message"
}

notify::update() {
  # @TODO avoid too many request at the same time
  local sleep_time=$(os::random_int 600)
  if [ -n "$DEBUG" ]; then
    echo "waiting time: $sleep_time"
  fi
  sleep $sleep_time

  notify::update::now "$@"
}

export -f notify::feishu

export -f notify::update
export -f notify::update::now