#!/bin/bash

notify::feishu() {
  local url=$1
  local title=$2
  local message=$3
  local data_part1='{"msg_type":"post","content":{"post":{"zh_cn":{"title":"'
  local data_part2='","content":[[{"tag": "text", "text": "'
  local data_part3='" }]]}}}}'

  local data="${data_part1}${title}${data_part2}${message}${data_part3}"
  
  # echo "data: $data"

  curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d "$data" \
    $url >> /dev/null 2>&1
}

notify::update() {
  local version_change=$@

  local url="https://open.feishu.cn/open-apis/bot/v2/hook/143f1ab2-98a7-4334-93d6-c27bb5050e07"
  local ip=$(zmicro machine ip)
  local user=$(os::username)
  local homedir=$(os::homedir)
  local shell=$(os::shell)
  local id=$(os::machine_id)
  local uptime=$(uptime)
  local hostname=$(os::hostname)
  local kernel=$(os::kernel)
  local release="-"
  local architecture=$(os::arch)
  local is_docker=false
  local device_config="-"
  local load="-"
  local timestamp=$(os::timestamp)

  if [ "$(os::is_macos)" != "true" ]; then
    release=$(os::release)
    is_docker=$(os::is_docker)
    device_config=$(os::device_config)
    load="cpu: $(os::memory_usage percent)%, memory: $(os::memory_usage percent)%, disk: $(os::disk_usage percent)%"
  fi

  local message="\
## Network\n\
* ip: $ip\n\
\n\
## User\n\
* user: $user\n\
* homedir: $homedir\n\
* shell: $shell\n\
* hostname: $hostname\n\
\n\
## System\n\
* kernel: $kernel\n\
* release: $release\n\
* arch: $architecture\n\
* is_docker: $is_docker\n\
\n\
## Device\n\
* id: $id\n\
* device_config: $device_config\n\
\n\
## Load\n\
* load: $load\n\
* uptime: $uptime\n\
\n\
* timestamp: $timestamp"

  notify::feishu $url "[ZMICRO][更新][${version_change}] $ip - $user - $kernel - $release" "$message"
}

export -f notify::feishu

export -f notify::update