#!/bin/bash

function test_os::kernel() {
  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$(uname -s)" \
    "$(os::kernel)"
}

function test_os::fn() {
  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "a/b:latest,a/b:v1,a/b:v1.2,a/b:v1.2.1" \
    "$(os::fn tag::docker a/b v1.2.1)"
}
