#!/bin/bash

function test_path::resolve() {
  testing::expect \
    "${FUNCNAME[0]} - relative" \
    "to_equal" \
    "$PWD/bin/zmicro" \
    "$(path::resolve bin/zmicro)" 
  
  testing::expect \
    "${FUNCNAME[0]} - relative dot" \
    "to_equal" \
    "$PWD/bin/zmicro" \
    "$(path::resolve ./bin/zmicro)" 

  testing::expect \
    "${FUNCNAME[0]} - relative dot dot" \
    "to_equal" \
    "$(dirname $PWD)/bin/zmicro" \
    "$(path::resolve ../bin/zmicro)" 
  
  testing::expect \
    "${FUNCNAME[0]} - absolute" \
    "to_equal" \
    "/bin/zmicro" \
    "$(path::resolve /bin/zmicro)" 
}
