#!/bin/bash

get_current_path() {
  echo $(realpath $(dirname "$0"))
}

is_file() {
  path=$1
  if [ -f $path ]; then
    return 0
  fi

  return 1
}

is_dir() {
  path=$1
  if [ -d $path ]; then
    return 0
  fi

  return 1
}

path_basename() {
  local path=$1

  if [ "$path" = "" ]; then
    log_error "path is required"
    exit 1
  fi

  echo $(string_split_last_element '/' $path)
}

path_dirname() {
  local path=$1

  if [ "$path" = "" ]; then
    log_error "path is required"
    exit 1
  fi

  echo "/$(string_split_slice '/' $path 0 -1)"
}

path_join() {
  local str=$(array_join '/' $@)
  # echo $str
  echo $(string_replace $str '/\{2,\}' '/')
}

realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}


export -f get_current_path
export -f is_file
export -f is_dir

export -f path_basename
export -f path_dirname
export -f path_join

export -f realpath
