#!/bin/bash

plugin_register() {
  local plugin_name=$1
  if [ "$plugin_name" = "" ]; then
    log_error "[$(timestamps)][plugin] register: plugin name is required"
    exit 1
  fi

  local plugin_path=$(plugin_path $plugin_name)
  local plugin_bin_path=$(plugin_bin_path $plugin_name)

  if [ ! -d $plugin_bin_path ]; then
    # exit 0
    return
  fi

  log_debug "[$(timestamps)][plugin] bins_path: $plugin_bin_path"
  local bins=$(plugin_list_bins $plugin_name)
  for bin in $bins; do
    local bin_path=$ZMICRO_HOME/bin/$bin

    if [ -f "$bin_path" ] || [ -x "$bin_path" ]; then
      log_warn "[$(timestamps)][plugin] $(color_red "remove") old bin: $bin"
      rm $bin_path
    fi

    log_success "[$(timestamps)][plugin] $(color_green "register") $plugin_name bin: $(color_success $bin)"
    ln -s $plugin_bin_path/$bin $bin_path
  done
}

plugin_unregister() {
  local plugin_name=$1
  if [ "$plugin_name" = "" ]; then
    log_error "[$(timestamps)][plugin] register: plugin name is required"
    exit 1
  fi

  local plugin_path=$ZMICRO_PLUGIN_PATH/$plugin_name

  if [ ! -d $plugin_path/$plugin/bin ]; then
    # exit 0
    return
  fi

  log_debug "[$(timestamps)][plugin] bins_path: $plugin_path/$plugin/bin"
  local bins=$(plugin_list_bins $plugin_name)
  for bin in $bins; do
    local bin_path=$ZMICRO_HOME/bin/$bin

    if [ -f "$bin_path" ] || [ -x "$bin_path" ]; then
      log_success "[$(timestamps)][plugin] $(color_red "unregister") $plugin_name bin: $(color_red $bin)"
      rm $bin_path
    fi
  done
}

plugin_register_all() {
  local plugin_path=$1
  if [ "$plugin_path" = "-" ]; then
    return
  fi

  local plugins=$(ls $plugin_path)

  log_debug "\n\n[$(timestamps)][plugin]"
  for plugin in $plugins; do
    log_debug "[$(timestamps)][plugin] find plugin: $plugin"

    if [ ! -d "$plugin_path/$plugin/bin" ]; then
      continue
    fi

    log_debug "[$(timestamps)][plugin] bins_path: $plugin_path/$plugin/bin"
    local bins=$(ls $plugin_path/$plugin/bin)
    for bin in $bins; do
      local bin_path=$ZMICRO_HOME/bin/$bin

      if [ ! -f "$bin_path" ] && [ ! -x "$bin_path" ]; then
        log_debug "[$(timestamps)][plugin] register $plugin bin: $bin"

        ln -s $plugin_path/$plugin/bin/$bin $ZMICRO_HOME/bin/$bin
      fi
    done
  done
}

plugin_path() {
  local plugin_name=$1
  echo $ZMICRO_PLUGIN_PATH/$plugin_name
}

plugin_bin_path() {
  local plugin_name=$1
  echo $ZMICRO_PLUGIN_PATH/$plugin_name/bin
}

plugin_exist() {
  if [ -d $(plugin_path $1) ]; then
    echo "true"
  else
    echo "false"
  fi
}

plugin_bin_exist() {
  if [ -d $(plugin_bin_path $1) ]; then
    echo "true"
  else
    echo "false"
  fi
}

plugin_list_names() {
  echo $(ls $ZMICRO_PLUGIN_PATH)
}

plugin_list_bins() {
  local plugin_name=$1
  if [ "$(plugin_exist $plugin_name)" != "true" ]; then
    echo ""
  else
    ls $(plugin_bin_path $plugin_name)
  fi
}

plugin_load_mod() {
  local plugin_name=$1
  local plugin_mod_path="$(plugin_path $plugin_name)/mod"

  if [ -f $plugin_mod_path ]; then
    \. $plugin_mod_path
  fi
}

plugin_get_version() {
  plugin_load_mod $1

  if [ "$PLUGIN_VERSION" = "" ]; then
    echo "-"
    return
  fi

  echo "$PLUGIN_VERSION"
}

plugin_get_description() {
  plugin_load_mod $1

  if [ "$PLUGIN_DESCRIPTION" = "" ]; then
    echo "No Description"
    return
  fi

  echo "$PLUGIN_DESCRIPTION"
}

plugin_each() {
  local fn=$1
  local plugins=$(plugin_list_names)
  array_each $fn $plugins
}

export -f plugin_register_all
export -f plugin_register
export -f plugin_unregister

export -f plugin_list_names
export -f plugin_list_bins
export -f plugin_each

export -f plugin_path
export -f plugin_bin_path
export -f plugin_exist
export -f plugin_bin_exist
export -f plugin_load_mod
export -f plugin_get_version
export -f plugin_get_description
