#!/bin/bash

pm() {
  which brew >>/dev/null 2>&1
  if [ "$?" = "0" ] && [ "$(os::is_macos)" = "true" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    brew $args
    return
  fi

  which yum >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo yum $@
    return
  fi

  which apt >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo apt $@
    return
  fi
}

# node npm
pm::npm() {
  if [ "$(os::is_nodejs_installed)" = "false" ]; then
    zpackage install nodejs
  fi

  # @TODO
  if [ "$(net::is_google_visitable)" = "false" ]; then
    export NPM_CONFIG_REGISTRY=https://registry.npm.taobao.org
  fi

  npm $@
}

export -f pm
export -f pm::npm