#!/bin/bash

pm() {
  which brew >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;

      *)
        args="$args $arg"
        ;;
      esac
    done

    brew $args
    return
  fi

  which yum >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo yum $@
    return
  fi

  which apt >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo apt $@
    return
  fi
}

# node npm
pm_npm() {
  # @TODO
  if [ "$(net_is_in_china)" = "true" ]; then
    export NPM_CONFIG_REGISTRY=https://registry.npm.taobao.org
  fi

  npm $@
}

pm_nvm() {
  # @TODO
  if [ "$(net_is_in_china)" = "true" ]; then
    export NVM_NODEJS_ORG_MIRROR=https://npm.taobao.org/dist 
  fi

  nvm $@
}

export -f pm
export -f pm_npm
export -f pm_nvm