#!/bin/bash

os::repl::scope() {
  local scope=$1

  while true; do
    while IFS="" read -r -e -d $'\n' -p "$scope> " args; do
      echo "xxx: $args"
      if [ "$args" = "quit" ]; then
        exit 0
      else
        "$scope" "$args"
      fi
    done
  done
}

os::repl() {
  while true; do
    local startFlag="$(color::success $)"
    while IFS="" read -r -e -d $'\n' -p $startFlag" " commandAndArgs; do
      local cmd=$(array::first_element $commandAndArgs)
      local args=$(array::slice 1 1000 $commandAndArgs)
      # echo "cmd: $cmd"
      # echo "args: $args"
      if [ "$cmd" = "quit" ]; then
        exit 0
      else
        command -v $cmd >>/dev/null 2>&1

        if [ "$?" != "0" ]; then
          zmicro $cmd $args
        else
          $cmd $args
        fi

        if [ "$?" != "0" ]; then
          startFlag="$(color::error $)"
        else
          startFlag="$(color::success $)"
        fi
      fi
    done
  done
}

export -f os::repl::scope
export -f os::repl
