#!/bin/bash

require() {
  local name=$1
  local version=$2
  local repo=$3
  local force_update=$IS_REQUIRE_MOD_UPDATE_TMP_GLOBAL

  if [ "$(zmicro plugin has $name)" = "true" ]; then
    # log::info "[require][update] ${name} ${version}"
    log::debug "[$(timestamp)][require] installed before (2): ${name}"

    if [ "$force_update" = "true" ]; then
      log::info "[$(timestamp)][require] update: ${name}"
      zmicro plugin update $name
    else
      log::info "[$(timestamp)][require] ${name} done"
    fi
    return
  fi

  # log::info "[require][install] ${name} ${version}"
  #@PACKAGE ^package_name@version
  if [ "$(string::match $name ^^)" = "true" ]; then
    name=$(echo $name | awk -F '^' '{print $2}')
    log::info "[$(timestamp)][require][package] install: $name ($version) ..."
    #
    zmicro package install $name@$version $repo
    if [ "$?" = "0" ]; then
      log::success "[$(timestamp)][require][package] install success: ${name}"
    else
      log::error "[$(timestamp)][require][package] install failed: ${name}"
    fi
    return
  fi

  # @PLUGIN plugin_name@version
  log::info "[$(timestamp)][require][plugin] install: $name ($version) ..."
  # log::info "[$(timestamp)][require] repo: ${repo}"
  # @TODO
  zmicro plugin install $name $version $repo
  if [ "$?" = "0" ]; then
    log::success "[$(timestamp)][require][plugin] install success: ${name}"
  else
    log::error "[$(timestamp)][require][plugin] install failed: ${name}"
  fi

  # sleep 1
}

require::parse() {
  # echo "require::parse: $@"
  # compose@v0.0.1
  local text=$2

  # echo "IS_REQUIRE_MOD_UPDATE_TMP_GLOBAL: $IS_REQUIRE_MOD_UPDATE_TMP_GLOBAL"
  # echo "is_require_mod_update: $is_require_mod_update"

  local name=$(echo $text | awk -F '@' '{print $1}')
  local version=$(echo $text | awk -F '@' '{print $2}' | awk -F '#' '{print $1}')
  local repo=$(echo $text | awk -F '#' '{print $2}')

  # echo "[require::parse] ${name}(${version}) - ${repo}"
  # log::info "[$(timestamp)][require] install plugin $name ($version) - ${repo} ..."
  require $name $version $repo
}

require::mod() {
  # @TODO overide core DEPENDENCIES
  if [ -n ${DEPENDENCIES} ]; then
    # echo "overide DEPENDENCIES"
    DEPENDENCIES=()
  fi

  local mod_path=$1
  local is_require_mod_update=false

  shift
  while [[ $# -gt 0 ]]; do
    local key=$1
    local value=$2
    case $key in
    -u | --update)
      os::set_var is_require_mod_update true
      shift
      ;;
    *)
      if [ "$(string::match $key ^-)" = "true" ]; then
        log::error "[require::mod] ERROR: unknown parameter \"$key\""
        exit 1
      fi

      shift
      ;;
    esac
  done

  # @TODO cannot pass params in array::each, so use global instead of
  IS_REQUIRE_MOD_UPDATE_TMP_GLOBAL=$is_require_mod_update

  # load mod
  config::load_file $mod_path

  # ignore update dependencies
  if [ -n "$NO_DEPENDENCIES" ]; then
    return
  fi

  if [ -n $DEPENDENCIES ]; then
    local dependeny_count=$(array::length ${DEPENDENCIES[@]})
    if [ "$dependeny_count" = "0" ]; then
      return
    fi

    log::info "[$(timestamp)][require] found depdencies: $(color::green ${dependeny_count}) ..."
    echo ""

    array::each require::parse ${DEPENDENCIES[@]}

    # echo $DEPENDENCIES
    # for one in ${DEPENDENCIES[@]}; do
    #   echo "x: "$one
    # done

    # @TODO clean
    # export DEPENDENCIES=""
  fi
}

require::core_mod() {
  require::mod $ZMICRO_MOD $@
}

require::plugin_mod() {
  local plugin_name=$1
  if [ -z $plugin_name ]; then
    log::error "[require::plugin_mod] plugin name is required"
    exit 1
  fi

  # echo "plugin_name: $(plugin::get_mod_path $plugin_name)"
  # echo "${DEPENDENCIES[@]}"
  require::mod $(plugin::get_mod_path $plugin_name) $@
}

export -f require
export -f require::mod
export -f require::parse

export -f require::core_mod
export -f require::plugin_mod
