#!/bin/bash

tag::docker() {
  local name=$1
  local version=$2
  local prefix=$3
  
  if [ -z "$name" ]; then
    log::error "[tag::docker] name is required"
    exit 1
  fi

  if [ -z "$version" ]; then
    log::error "[tag::docker] version is required"
    exit 1
  fi

  if [ -z "$prefix" ]; then
    prefix="v"
  fi

  local major=$(version::get_major $version $prefix)
  local minor=$(version::get_minor $version $prefix)
  local patch=$(version::get_patch $version $prefix)

  echo "$name:$major,$name:$minor,$name:$patch"
}

export -f tag::docker
