#!/bin/bash

testing::expect() {
  local test_name=$1
  local test_func=$2
  local test_args=${@:3}

  log::info "  Case: $test_name"
  # log::info "  $test_func $test_args"
  eval "testing::expect::$test_func $test_args"
  # log::info "  $test_func $test_args"
}

testing::expect::to_equal() {
  local expected=$1
  local received=$2
  if [ "$received" != "$expected" ]; then
    log::error "    [$(timestamp)][expect_to_equal] expect($expected) but receive($received)"
    exit 1
  else
    log::success "    [$(timestamp)][expect_to_equal] ok (value: $expected)"
  fi
}

export -f testing::expect
export -f testing::expect::to_equal