#!/bin/bash

users::all() {
  if [ "$(os::is_macos)" = "true" ]; then
    echo "-"
    return
  fi

  ls /home
}

users::online() {
  who
}

users::login::histories() {
  last
}

users::doing() {
  w
}

export -f users::all
export -f users::online
export -f users::login::histories
export -f users::doing

