#!/bin/bash

version::update() {
  PREV=$ZMICRO_VERSION

  config::load_core_mod

  LATEST=$ZMICRO_VERSION

  # echo "Load Version: $ZMICRO_VERSION"
  # echo "BBB: $PREV => $LATEST"
  log::version $PREV $LATEST

  echo $LATEST
}

version::timestamp() {
  cd $ZMICRO_HOME
  git show -s --format=%cd --date="format:%Y-%m-%d"
}

version::get() {
  config::load_core_mod

  echo $ZMICRO_VERSION
}

version::git_hash() {
  cd $ZMICRO_HOME

  git rev-parse --short=9 HEAD
}

export -f version::get
export -f version::git_hash
export -f version::timestamp

export -f version::update