#!/bin/bash

function test_version::is_valid() {
  testing::expect \
    "${FUNCNAME[0]} - ok" \
    "to_equal" \
    "true" \
    "$(version::is_valid v1.2.3)" 
  
  testing::expect \
    "${FUNCNAME[0]} - ok" \
    "to_equal" \
    "true" \
    "$(version::is_valid v100.200.300)" 

  testing::expect \
    "${FUNCNAME[0]} - empty" \
    "to_equal" \
    "false" \
    "$(version::is_valid)" 
  
  testing::expect \
    "${FUNCNAME[0]} - not prefix v" \
    "to_equal" \
    "false" \
    "$(version::is_valid 1.2.3)" 

  testing::expect \
    "${FUNCNAME[0]} - not three 1" \
    "to_equal" \
    "false" \
    "$(version::is_valid v1)" 

  testing::expect \
    "${FUNCNAME[0]} - not three 2" \
    "to_equal" \
    "false" \
    "$(version::is_valid v1.2)" 
}
