#!/bin/bash

update_version() {
  PREV=$ZMICRO_VERSION

  config::load_core_mod

  LATEST=$ZMICRO_VERSION

  # echo "Load Version: $ZMICRO_VERSION"
  # echo "BBB: $PREV => $LATEST"
  log::version $PREV $LATEST

  echo $LATEST
}

get_current_version() {
  config::load_core_mod
  
  echo $ZMICRO_VERSION
}

get_version() {
  get_current_version
}

export -f update_version
export -f get_version
export -f get_current_version
