#!/bin/bash

. $ZMICRO_HOME/commands/machine/lvm/config

is_lvm_created() {
  sudo vgs | grep $VG_NAME >> /dev/null 2>&1
  if [ "$?" != "0" ]; then
    echo "false"
    return
  fi

  echo "true"
}

is_device() {
  local device=$1
  echo $device | grep "^/dev/" >> /dev/null 2>&1
  if [ "$?" = "0" ]; then
    echo "true"
    return
  fi

  echo "false"
}

remove() {
  local device=$1
  # /dev/sda => sda
  local deviceName=$(echo $device | sed -e "s%/dev/%%g")

  if [ "$VG_NAME" = "" ] || [ "$LV_NAME" = "" ] || [ "$MOUNT_PATH" = "" ]; then
    log_error "lvm config not load"
    exit 1
  fi

  if [ "$(is_device $device)" = "false" ]; then
    log_error "device should start with /dev/*, but found: ${device}"
    exit 1
  fi

  # 1.initial physical volume
  sudo pvs | grep $device >> /dev/null 2>&1
  if [ "$?" != "0" ]; then
    log_success "lvm device(${device}) not found, maybe removed before"
    exit 0
  fi

  sudo pvremove $device
  log_success "remove lvm device success: ${device}"
}

help() {
  echo "Usage:"
  echo "  zmicro machine lvm remove <device>"
  echo ""
  echo "Example:"
  echo "  remove /dev/sda:"
  echo "    zmicro machine lvm remove /dev/sda"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local device=$1
  if [ "$device" = "" ]; then
    log_error "device is required"
    exit 1
  fi

  remove $device
}

run() {
  core $@
}

run $@
