#!/bin/bash

disk_usage=$(zmicro machine disk usage)
is_health=$(zmicro machine disk healthcheck)

echo -e "Disk Usage: ${disk_usage}%"

if [ "$is_health" = "true" ]; then
  echo -e "${GREEN}Disk Healthy: True${ENDCOLOR}"
else
  echo -e "${RED}Disk Healthy: False${ENDCOLOR}"
  echo -e "${RED}WARN: please check your disk first${ENDCOLOR}"
  exit 1
fi
