#!/bin/bash

export TZ=Asia/Shanghai

export TODAY=$(date +%Y-%m-%d)

# Core
export ZMICRO_NAME=zmicro
export ZMICRO_HOME=${ZMICRO_HOME:-"/usr/local/lib/zmicro"}
export ZMICRO_BIN=$ZMICRO_HOME/bin/zmicro
export ZMICRO_LOCAL_BIN=/usr/local/bin/zmicro

# Repo
export ZMICRO_GIT=https://github.com/zcorky/zmicro

# RC
export ZMICRO_GLOBAL_RC_DIR=/etc/zmicro
export ZMICRO_GLOBAL_RC=$ZMICRO_GLOBAL_RC_DIR/.zmicrorc
export ZMICRO_RC=$HOME/.zmicrorc

# Mod
export ZMICRO_MOD=$ZMICRO_HOME/mod

# Log
export ZMICRO_LOG_DIR=${ZMICRO_LOG_DIR:-"/var/log/${ZMICRO_NAME}"}
# @TODO
if [ "$ZMICRO_HOME" != "/usr/local/lib/zmicro" ]; then
  ZMICRO_LOG_DIR=/tmp/zmicro
  if [ ! -d "$ZMICRO_LOG_DIR" ]; then
    mkdir -p $ZMICRO_LOG_DIR
  fi
fi

# @DEPRECIATED ZMICRO_LOG_DIR
export ZMICRO_LOG_PATH=$ZMICRO_LOG_DIR #/tmp/zmicro

# Lock
export ZMICRO_LOCK_UPDATE_PATH=$ZMICRO_LOG_PATH/update.lock

export ZMICRO_LOG_COMMON_PATH=$ZMICRO_LOG_PATH/common.$TODAY.log
export ZMICRO_LOG_DEBUG_PATH=$ZMICRO_LOG_PATH/debug.log
export ZMICRO_LOG_ERROR_PATH=$ZMICRO_LOG_PATH/error.log

export ZMICRO_LOG_UPDATE_PATH=$ZMICRO_LOG_PATH/update.log
export ZMICRO_LOG_VERSION_PATH=$ZMICRO_LOG_PATH/version.log
export ZMICRO_LOG_NOTIFY_PATH=$ZMICRO_LOG_PATH/notify.log

# Data
export ZMICRO_APP_DATA_PATH=/data
# Logs
export ZMICRO_APP_LOGS_PATH=/logs
# Configs
export ZMICRO_APP_CONFIGS_PATH=/configs

# @TODO MAC
[[ "$(uname -s)" = "Darwin" ]] && export ZMICRO_APP_DATA_PATH=/opt/data
[[ "$(uname -s)" = "Darwin" ]] && export ZMICRO_APP_LOGS_PATH=/opt/logs
[[ "$(uname -s)" = "Darwin" ]] && export ZMICRO_APP_CONFIGS_PATH=/opt/configs

# Plugin
export ZMICRO_PLUGINS_PATH=$ZMICRO_HOME/plugins

export ZMICRO_REPO_ORGANIZATION=zmicro-design
export ZMICRO_PLUGIN_GITHUB_DEFAULT_PROXY=https://github.whateverhappens.org
export ZMICRO_PLUGIN_GITHUB="https://github.com"
export ZMICRO_PLUGIN_GITHUB_PROXY=${ZMICRO_PLUGIN_GITHUB_PROXY}
export ZMICRO_PLUGIN_REPO_PREFIX="${ZMICRO_PLUGIN_GITHUB_PROXY:-$ZMICRO_PLUGIN_GITHUB}/${ZMICRO_REPO_ORGANIZATION}/plugin-"

export ZMICRO_PLUGINS_DATA_PATH=$ZMICRO_APP_DATA_PATH/plugins
export ZMICRO_PLUGINS_LOGS_PATH=$ZMICRO_APP_LOGS_PATH/plugins
export ZMICRO_PLUGINS_CONFIGS_PATH=$ZMICRO_APP_CONFIGS_PATH/plugins

# PATHS
export ZMICRO_BIN_PATH=$ZMICRO_HOME/bin #$(realpath $(dirname "$0"))
export ZMICRO_SUB_BIN_PATH=$ZMICRO_BIN_PATH/sub
export ZMICRO_USER_BIN_PATH=$ZMICRO_BIN_PATH/user
export ZMICRO_CORE_PATH=$ZMICRO_HOME/core
export ZMICRO_CONFIGS_PATH=$ZMICRO_HOME/config
export ZMICRO_COMMANDS_PATH=$ZMICRO_HOME/commands
export ZMICRO_SERVICES_PATH=$ZMICRO_HOME/services

# export DATA_INFLUX_PATH=$ZMICRO_APP_DATA_PATH/influx
# export DATA_POSTGRES_PATH=$ZMICRO_APP_DATA_PATH/postgres

# DEFAULT GIT
export DEFAULT_GIT_USERNAME=${GIT_USER:-$USER}
export DEFAULT_GIT_PASSWORD=${GIT_PASSWORD}
export DEFAULT_GIT_EMAIL=${GIT_EMAIL:-$USER@local}

export ZMICRO_REPORT_URL=https://open.feishu.cn/open-apis/bot/v2/hook/143f1ab2-98a7-4334-93d6-c27bb5050e07
export ZMICRO_UPDATE_REPORT_URL=$ZMICRO_REPORT_URL
export ZMICRO_UPDATE_REPORT_LOG_URL=https://api.zcorky.com/logs/zmicro-updates
export ZMICRO_LOGIN_REPORT_URL=https://open.feishu.cn/open-apis/bot/v2/hook/569c3a71-a5ef-46c2-a98b-4c9b63893483
export ZMICRO_LOGIN_REPORT_LOG_URL=https://api.zcorky.com/logs/zmicro-logins

export ZMICRO_SCRIPT_RECORD_TIMESTAMP=/tmp/zmicro_script_record_tmp.timestamp
export ZMICRO_SCRIPT_RECORD_COMMANDS=/tmp/zmicro_script_record_tmp.commands

export ZMICRO_AUTO_UPDATE_EVERY_DAY_HOUR=11

# LOG_LEVEL is the log level, default: info
#  available:
#    info
#    warn
#    debug
#    error
#    fatal
export LOG_LEVEL=${LOG_LEVEL:-info}
