#!/bin/bash

# @TODO
#  cannot use export AVAILABLE_PACKAGES
AVAILABLE_PACKAGES=(
  "frp"
  "sync"
  "tldr"
  "inlets"
  "rsa"
  "acme"
  "cheat"
  "nps"
  "exa"
  "lsd"
  "dust"
  "duf"
  "broot"
  "fd"
  "fzf"
  "curlie"
  "gotop"
  "htop"
  "tig"
  "ffmpeg"
  "tmux"
  "you-get"
  "youtube-dl"
  "gh"
  "fkill"
  "mtr"
)
