#!/bin/bash
DEFAULT_NETWORK=ingress
COMPOSE_BIN_PATH=/usr/bin/docker-compose
COMPOSE_VERSION=1.29.1

# Returning a boolean from a bash function
#   [Solved]: Stack Overflow: https://stackoverflow.com/questions/5431909/returning-a-boolean-from-a-bash-function
#
is_docker_installed() {
  which docker >> /dev/null 2>&1
  if [ "$?" != "0" ]; then
    return 1
  fi

  return 0
}

try_to_remove_podman() {
  which podman >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    log "Found podman, removing ..."
    pm remove -y podman
    sudo rm -rf `which docker`

    log "Upgrade Docker ..."
  fi
}

remove_docker_core() {
  pm remove -y docker-ce docker-ce-cli containerd.io
}

remove_docker_compose() {
  if [ -f $COMPOSE_BIN_PATH ]; then
    sudo rm $COMPOSE_BIN_PATH
  fi
}

stop_docker() {
  sudo systemctl stop docker
  sudo systemctl disable docker
}

# Dangerous
# remove_images_volumes_conatiners() {
#   sudo rm -rf /var/lib/docker
#   sudo rm -rf /var/lib/containerd
# }

remove_docker() {
  try_to_remove_podman

  # Returning a boolean from a bash function
  #   Useage
  if ! is_docker_installed; then
    log "Cannot found docker or docker has been already removed before."
    exit 0
  fi

  log "Stop Docker Daemon ..."
  stop_docker

  log "Remove Docker ..."
  remove_docker_core

  log "Remove Docker Compose ..."
  remove_docker_compose
}

remove_docker