#!/bin/bash

remove_nodejs() {
  NVM_DIR=$HOME/.nvm

  if [ ! -d $NVM_DIR ]; then
    echo "Nodejs has already been removed."
    exit 0
  fi

  echo -e "Find nodejs in $NVMDIR, removing ..."
  rm -rf $NVM_DIR
  echo "Remove nodejs done."
}

remove_nodejs