#!/bin/bash

# CURRENT_PATH=$(get_current_path)
CURRENT_PATH=$ZMICRO_CORE_PATH/inquirer

which bc >>/dev/null 2>&1
if [ "$?" != "0" ]; then
  pm install -yqq bc
fi


# echo "TERM: $TERM"

if [ "$TERM" = "" ] || [ "$TERM" = "dumb" ]; then
  # fix background: No value for $TERM and no -T specified
  tput() {
    return
  }

  export -f tput
fi

. $CURRENT_PATH/inquirer::text
. $CURRENT_PATH/inquirer::select
