#!/bin/bash

# CURRENT_PATH=$(get_current_path)
CURRENT_PATH=$ZMICRO_CORE_PATH/inquirer

which bc >>/dev/null 2>&1
if [ "$?" != "0" ]; then
  pm install -yqq bc
fi

. $CURRENT_PATH/inquirer_text
. $CURRENT_PATH/inquirer_select
