#!/bin/bash

. $ZMICRO_HOME/core/env

help() {
  echo "Usage:"
  echo "  zmicro apply [option] <service>"
  echo ""
  echo "Options:"
  echo "    -r,--remove Remove apply service"
  echo ""
  echo "Services:"
  echo "    proxy       Apply proxy for commandline"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local option=$1
  local service=$2

  if [ -z "$service" ]; then
    service=$option
    option=""
  fi

  local option_remove=false
  case $option in
    -r | --remove)
      option_remove=true
      ;;
  esac


  case $service in
  proxy)
    if [ "$option_remove" = "true" ]; then
      zmicro proxy remove
    else
      zmicro proxy apply
    fi
    ;;
  *)
    log::info "unknown command: $1"
    help
    exit 0
    ;;
  esac
}

run() {
  core $@
}

run $@
