#!/bin/bash

. $ZMICRO_HOME/core/env

PLUGIN=daemon

help() {
  zmicro plugin run ${PLUGIN} --help
}

dependency_check() {
  if [ "$(plugin_exist ${PLUGIN})" = "false" ]; then
    log_info "plugin ${PLUGIN} is required, installing ..."

    zmicro plugin install ${PLUGIN}
  fi
}

core() {
  dependency_check

  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro plugin run ${PLUGIN} $@
}

run() {
  core $@
}

run $@
