#!/bin/bash

load inquirer

required() {
  if [ "$1" = "" ]; then
    echo false
  else
    echo true
  fi
}

create() {
  local service_name=$1
  local service_command=""
  if [ "$service_name" = "" ]; then
    inquirer_text "daemon service name:" service_name "" "service name is required" required
  fi

  inquirer_text "daemon service command:" service_command "" "service command is required" required

  log_info ""
  log_info "create service ..."
  log_info "#################################"
  log_info "service_name: $service_name"
  log_info "service_command: $service_command"
  log_info "#################################"

  local yesno=('Yes' 'No')
  inquirer_select "is it ok ?" yesno answer
  if [ "$answer" != "Yes" ]; then
    exit 0
  fi

  # log_info "Yes"
  daemon_create $service_name $service_command
}

help() {
  echo "Usage:"
  echo "  zmicro daemon <action> <app_name>"
  echo ""
  echo "  Actions:"
  echo "    create    Create a new daemon service"
  echo "    remove    Remove a new daemon service"
  echo "    start     Start daemon service"
  echo "    stop      Stop daemon service"
  echo "    restart   Restart daemon service"
  echo "    reaload   Reload daemon service"
  echo "    enable    Enable daemon service when system start up"
  echo "    disable   Disable daemon service when system start up"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local action=$1
  local name=$2
  if [ "$action" = "" ]; then
    log_error "action is required"
    help
    exit 1
  fi

  case $action in
    create)
      create $name
      ;;
    *)
      eval "daemon_${action} ${name}"
      ;;
  esac
}

run() {
  core $@
}

run $@
