#!/bin/bash

. $ZMICRO_HOME/core/env

help() {
  echo "Delay 1s fn"
  echo ""
  echo "Usage:"
  echo "  zmicro delay <fn_name> <fn_args...>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local fn=$1
  local args=${@:2}

  delay $fn $args
}

run() {
  core $@
}

run $@
