#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro docs <module | method> <name>"
  echo ""
  echo "Examples:"
  echo "  zmicro docs module plugin"
  echo "  zmicro docs method plugin::run_nodejs"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local module=$1
  local name=$2

  case $module in
  module)
    docs::module $name
    ;;
  method)
    docs::method $name
    ;;
  *)
    log::error "[$(timestamp)] unknown module: $module"
    help
    ;;
  esac
}

run() {
  core "$@"
}

run "$@"
