#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro dotenv <command> <args...>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ -z "$1" ]; then
    help
    exit 0
  fi

  dotenv::try_load

  local is_forever=false
  if [ "$FOREVER" = "true" ] || [ "$SUPERVISOR" = "true" ]; then
    is_forever=true
  fi

  # local command=$1
  # local args="${@:2}"

  if [ "$is_forever" = "true" ]; then
    os::forever "$@"
  else
    eval "$@"
  fi
}

run() {
  core "$@"
}

run "$@"
