#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro exec <shell_script> <shell_script_args...>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ -z "$1" ]; then
    help
    exit 0
  fi

  dotenv::try_load

  local shell_script=$1
  local shell_script_args=${@:2}
  local is_forever=false
  if [ "$FOREVER" = "true" ] || [ "$SUPERVISOR" = "true" ]; then
    is_forever=true
  fi

  command -v $shell_script >>/dev/null 2>&1
  if [ $? -eq 0 ]; then
    local built_in_command=$shell_script

    if [ "$is_forever" = "true" ]; then
      os::forever $built_in_command $shell_script_args
    else
      $built_in_command $shell_script_args
    fi
    return
  fi

  # fix: a.sh => ./a.sh
  # fix: bin/a.sh => ./bin/a.sh
  # normal: /a.sh => /a.sh
  # normal: /bin/a.sh => /bin/a.sh
  if [ "${shell_script:0:1}" != "/" ] && [ "${shell_script:0:1}" != "." ]; then
    shell_script="./$shell_script"
  fi

  # @TODO
  set +e

  if [ -f "$shell_script" ]; then
    if [ "$is_forever" = "true" ]; then
      os::forever bash $shell_script $shell_script_args
    else
      bash $shell_script $shell_script_args
    fi
    return
  fi

  log::error "script $shell_script not found"

  # @TODO
  set -e
}

run() {
  core "$@"
}

run "$@"
