#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro fn <fn_name> <fn_args...>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  os::fn "$@"

  # @TODO
  # set -e
}

run() {
  core "$@"
}

run "$@"
