#!/bin/bash

help() {
  echp "Forever run command"
  echo ""
  echo "Usage:"
  echo "  zmicro forever [options ...] -- <command...>"
  echo ""
  echo "Options:"
  echo "  -d, --delay <seconds>  delay seconds"
  echo "  -i, --interval <seconds>  interval seconds"
  echo ""
  echo "Example:"
  echo "  zmicro forever -- npm run prod"
  echo "  zmicro forever --delay 1 -- npm run prod"
  exit 1
}

core() {
  os::forever "$@"
}

run() {
  core "$@"
}

run "$@"
