#!/bin/bash

. $ZMICRO_HOME/core/env

help() {
  echo "Usage:"
  echo "  zmicro go <where>"
}

core() {
  local where=$1
  local name=$2
  if [ "$where" = "-h" ] || [ "$where" = "--help" ]; then
    help
    exit 1
  fi

  if [ -z "$where" ]; then
    where="home"
  fi

  # # where => default plugin when name exist
  # # zmicro go package
  # #   => zmicro go plugin package
  # if [ -n "$where" ] && [ "$where" != "home" ] && [ "$where" != "plugin" ] && [ "$where" != "service" ] && [ "$where" != "package" ]; then
  #   where="plugin"
  #   name=$1
  # fi

  # echo "where: $where"
  # echo "name: $name"

  case $where in
    home)
      cd $ZMICRO_HOME
      exec $SHELL
      ;;
    plugin)
      if [ -z "$name" ]; then
        log::error "plugin name is required"
        exit 1
      fi

      local plugin_path=$ZMICRO_HOME/plugins/$name
      if [ ! -d $plugin_path ]; then
        log::error "plugin (${name}) not found"
        exit 1
      fi

      cd $plugin_path
      exec $SHELL
      ;;
    service)
      local path=$ZMICRO_HOME/plugins/${where}
      if [ ! -d $path ]; then
        log::error "plugin(${where}) not found (1)"
        exit 1
      fi

      if [ -n "$name" ]; then
        path=$path/${where}s/$name        
      fi
      if [ ! -d $path ]; then
        log::error "${where}(${name}) not found"
        exit 1
      fi

      cd $path
      exec $SHELL
      ;;
    package)
      local path=$ZMICRO_HOME/plugins/${where}
      if [ ! -d $path ]; then
        log::error "package(${where}) not found (2)"
        exit 1
      fi

      if [ -n "$name" ]; then
        path=$path/${where}s/$name        
      fi
      if [ ! -d $path ]; then
        log::error "${where}(${name}) not found"
        exit 1
      fi

      cd $path
      exec $SHELL
      ;;
    *)
      # fallback to plugin
      name=$where
      
      if [ -z "$name" ]; then
        log::error "plugin name is required"
        exit 1
      fi

      local plugin_path=$ZMICRO_HOME/plugins/$name
      if [ ! -d $plugin_path ]; then
        log::error "plugin (${name}) not found (3)"
        exit 1
      fi

      cd $plugin_path
      exec $SHELL
      ;;
  esac
}

run() {
  core $@
}

run $@
