#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro info"
}

core() {
  log::info "zmicro: $(zmicro version)"

  config::load_file $ZMICRO_HOME/mod
  for dependency in ${DEPENDENCIES[@]}; do
    local name=$(echo $dependency | awk -F '@' '{print $1}')
    local version=$(plugin::version_echo $name)
    log::info "  $name: $version"
  done

  log::info ""
  log::info "os:"
  log::info "  release: $(os::release)"
  log::info "  arch: $(os::arch)"
  log::info "  kernel: $(os::kernel)"
  log::info "  distribution: $(os::distribution)"
  log::info "  platform: $(os::platform)"
  log::info "  device: $(os::device_config)"
  log::info ""
  log::info "network:"
  log::info "  internal ip: $(net::get_ip_internal)"
  log::info "  external ip: $(net::get_ip)"
}

run() {
  core $@
}

run $@
