#!/bin/bash

set -e

clone_git() {
  # install
  if [ ! -d $ZMICRO_HOME ]; then
    git clone $ZMICRO_GIT -b $ZMICRO_VERSION $ZMICRO_HOME
    # git clone $ZMICRO_GIT -b master $ZMICRO_HOME
  else
    echo "Already Installed, if you want to update, run 'zmicro update'"
  fi
}

init() {
  PATH=$ZMICRO_BIN_PATH:$PATH
  zmicro config rc

  zmicro config version
  zmicro config logs
  zmicro config data
  # zmicro config git
  # zmicro config timezone

    # Do for MacOS
  if [ "$(os_is_macos)" != "true" ]; then
    zmicro config locale
    zmicro config timezone
  fi

  # $ZMICRO_BIN_PATH/zmicro config git $USER $USER"@local"
  zmicro config git # $GIT_USERNAME $GIT_EMAIL

  clone_git

  # install_dependencies
}

init
