#!/bin/bash

. $ZMICRO_HOME/core/env

help() {
  echo "Usage:"
  echo "  zmicro inlets [options]"
}

core() {
  # if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  #   help
  #   exit 0
  # fi

  # @TODO
  set +e

  which inlets >> /dev/null 2>&1
  if [ "$?" != "0" ]; then
    zmicro package install inlets
  fi

  inlets $@

  # @TODO
  set -e
}

run() {
  core $@
}

run $@
