#!/bin/bash

. $ZMICRO_HOME/core/env

help() {
  echo "Install zmicro plugin"
  echo ""
  echo "Usage:"
  echo "  zmicro install <plugin>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro plugin install $1
}

run() {
  core $@
}

run $@
