#!/bin/bash

. $ZMICRO_HOME/core/env

PLUGIN=package

help() {
  echo "Usage:"
  echo "  zmicro service <action> <service_name>"
}

dependency_check() {
  if [ "$(plugin_exist ${PLUGIN})" = "false" ]; then
    log_info "plugin ${PLUGIN} is required, installing ..."

    zmicro plugin install ${PLUGIN}
  # else
  #   zmicro plugin update ${PLUGIN}
  fi
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  dependency_check

  zmicro plugin run ${PLUGIN} $@
}

run() {
  core $@
}

run $@
