#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro proxy <ip>"
  echo ""
  echo "Example:"
  echo "    zmicro proxy apply"
  echo "    zmicro proxy 127.0.0.1:17890"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local ip=$1
  local port=$2

  # @TODO
  # zmicro proxy apply
  if [ "$ip" = "apply" ]; then
    ip=$(zmicro config get PROXY_IP)
    port=$(zmicro config get PROXY_PORT)

    if [ "$ip" = "" ]; then
      ip="127.0.0.1"
      port="17890"
    fi
  elif [ "$ip" = "remove" ]; then
    # zmicro proxy remove
    unset HTTPS_PROXY
    unset HTTP_PROXY
    unset https_proxy
    unset http_proxy

    log::success "You have removed proxy commandline."
    exec $SHELL
    exit 0
  fi

  if [ -z "$ip" ]; then
    log::error "proxy ip is required"
    exit 1
  fi

  if [ -z "$port" ]; then
    log::error "proxy port is required"
    exit 1
  fi

  if [ "$(net::is_port_visitable $ip $port)" != "true" ]; then
    log::error "ClashZ is not running, please check"
    exit 1
  fi

  # already running
  if [ "$HTTPS_PROXY" = "http://$ip:$port" ]; then
    log::info "You have already applied proxy commandline."
    exit 0
  fi

  export PROXY_IP=$ip
  export PROXY_PORT=$port
  export https_proxy=http://$ip:$port http_proxy=http://$ip:$port all_proxy=socks5://$ip:$port
  export HTTPS_PROXY=http://$ip:$port HTTP_PROXY=http://$ip:$port ALL_PROXY=socks5://$ip:$port

  # fix manpath: can't set the locale; make sure $LC_* and $LANG are correct
  export LC_CTYPE=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8

  # @TODO apply in new shell
  #   @TODO can apply current shell ???
  log::success "You have applied proxy commandline."

  exec $SHELL
}

run() {
  core $@
}

run $@
