#!/bin/bash

. $ZMICRO_HOME/core/env

help() {
  echo "reinstall zmicro"
  echo ""
  echo "Usage:"
  echo "  zmicro reinstall <self | plugin>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro install $@
}

run() {
  core $@
}

run $@

