#!/bin/bash

help() {
  echo "Run - Alias of Exec"
  echo ""
  echo "Usage:"
  echo "  zmicro run <command> <command_args...>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ -z "$1" ]; then
    help
    exit 0
  fi

  zmicro exec "$@"
}

run() {
  core "$@"
}

run "$@"
