#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro top [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  os::top
}

run() {
  core $@
}

run $@
