#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro version [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local version=$(version::get)
  local git_hash=$(version::git_hash)
  local timestamp=$(version::timestamp)

  echo "$(color::green $version) (${git_hash} ${timestamp})"
}

run() {
  core $@
}

run $@
