#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro service list [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro_service_list $@
}

run() {
  core $@
}

run $@
