#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro service reload <service_name> [options...]"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # Exit when met error
  set -e

  local service_name=$1
  local args=${@:2}
  zmicro_service_run $service_name restart $args
}

run() {
  core $@
}

run $@
