#!/bin/bash

help() {
  echo "List all the service"
  echo ""
  echo "Usage:"
  echo "  zmicro compose list"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name=$1
  local command=$2
  local args=${@:3}
  zmicro_service_run $service_name $command $args
}

run() {
  core $@
}

run $@
