#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro setup rust [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro package setup common
  
  zmicro package install rust
}

run() {
  set -e
  core $@
  set +e
}

run $@
