name: zmicro # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: "1.22.60" # just for humans, typically '1.2+git' or '1.3.2'
architectures: [amd64, arm64]
summary: Zero's Micro Server Tools Framework # 79 char long summary
description: |
  Zmicro is a linux server tools framework, also, manager, designed to manage
  linux server(packags/services) easily, also support MacOS.

license: MIT
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  zmicro:
    command: bin/zmicro

parts:
  zmicro:
    source: https://github.com/zcorky/zmicro/archive/refs/tags/v1.22.60.tar.gz
    plugin: dump
    source-type: tar
