name: Test in MacOS
on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 2 * * *"

jobs:
  on-success:
    needs: test
    runs-on: ubuntu-latest
    container: whatwewant/zmicro:v1
    if: ${{ always() && needs.test.result == 'success' }}
    steps:
      - name: Notification Feishu
        uses: whatwewant/action-robot-feishu@v0.0.13
        with:
          url: ${{ secrets.WORKFLOW_FEISHU_BOT_WEBHOOK_URL }}
          title: "✅ 自动化测试：${{ github.repository }}"
          text: |
            分支: ${{ github.ref }}
            提交信息: ${{ github.event.head_commit.message }}
            提交人: ${{ github.actor }}
            状态: 构建成功（https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}）

  on-failure:
    needs: test
    runs-on: ubuntu-latest
    container: whatwewant/zmicro:v1
    if: ${{ always() && needs.test.result == 'failure' }}
    steps:
      - name: Notification Feishu
        uses: whatwewant/action-robot-feishu@v0.0.13
        with:
          url: ${{ secrets.WORKFLOW_FEISHU_BOT_WEBHOOK_URL }}
          title: "❌ 自动化测试：${{ github.repository }}"
          text: |
            分支: ${{ github.ref }}
            提交信息: ${{ github.event.head_commit.message }}
            提交人: ${{ github.actor }}
            状态: 构建失败（https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}）

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    steps:
      - name: Install Zmicro
        run: curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | bash

      - name: Update Zmicro
        run: zmicro update -a

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Run test cases
        run: zmicro test core/

  # # test old version upgrade
  # test_v1_16:
  #   runs-on: ubuntu-latest
  #   container: whatwewant/zmicro:v1.16.32
  #   steps:
  #     - name: upgrade
  #       run: zmicro update -a
  #     - name: show version
  #       run: zmicro -v
  #     - name: show system info
  #       run: zmicro info

  # test_v1_9:
  #   runs-on: ubuntu-latest
  #   container: whatwewant/zmicro:v1.9.13
  #   steps:
  #     - name: upgrade
  #       run: zmicro update -a
  #     - name: show version
  #       run: zmicro -v
  #     - name: show system info
  #       run: zmicro info
